// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"
)

const addUser = `-- name: AddUser :one
INSERT INTO users (
  name
) VALUES (
  $1
)
RETURNING id, name
`

func (q *Queries) AddUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, addUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
